### ISSUE TITLE
add infer verbs?

### ISSUE THREAD

**Issue by topepo** [r-lib/generics#10]
`generate`, `calculate`, `hypothesize`, `specify`, and `visualize` are all pretty generic. 

I think that these are all simple functions that take tibbles so it might require overloading the classes to get a specific method what `infer` wants to do. 

@andrewpbray and @ismayc... any thoughts on this? This would enable others to use those verbs for their specific needs.

**Comment by ismayc** [comment]
I think this makes a lot of sense. I’m not exactly sure how others would use the verbs individually instead of in the {infer} pipeline though too, but I’m likely overlooking some use cases.

**Comment by hadley** [comment]
I don't think new functions should live here; this is specifically for base functions (or functions used by many existing packages) that should be generic. I think these functions would be a better fit for modelgenerics.

**Comment by ismayc** [comment]
I was assuming this repo and `modelgenerics` were the same thing based on the reroute. I'm not familiar with `modelgenerics` but agree with Hadley that these verbs aren't particularly useful unless some kind of modeling or testing is being done.

**Comment by topepo** [comment]
@ismayc we're probably going to send this to CRAN this week. Do you have any issues if I add those verbs? I don't see much downside.

**Comment by ismayc** [comment]
Nope. That works for us.

**Comment by topepo** [comment]
@ismayc Can you take a look at the new [branch](https://github.com/r-lib/generics/tree/infer-verbs)? 

I kept the signatures the same (mostly `x`).  Visualize uses `data`. If (or when) you make these methods in `infer`, would you consider changing that to `x` too?

**Comment by ismayc** [comment]
@topepo Looks good to me. We should probably switch to `x`. I’ll add that to the to-do list.

**Comment by topepo** [comment]
I'll change and do a PR. Thanks!
