### ISSUE TITLE
Don't use the `visible` column to determine if a method should be shown

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/generics#14]
Is the `visible` column of the `info` attribute in `utils::methods()` doing what we expect? Currently, this is used to determine if a method shows up in the dynamic documentation or not.

However, I was confused by the fact that even when you add the `\Sexpr` line to, say, the `tidy()` generic to generate the dynamic docs, and then load the dev version of `broom`, no methods show up.

`attr(utils::methods("tidy"), "info")` should show that all of the methods from broom are not visible.

Digging into the base code, `utils::methods()` calls `.S3methods()`, and this eventually calls the helper, `rbindSome()`, when it appends all of the S3 method information onto the `info` attribute. _`rbindSome()` sets `visible = FALSE` for ALL of the registered S3 methods._

This seems to be what is preventing the methods from showing up. Since methods like `tidy.zoo` have useful information, I would think we would want them to show up even though they are shown as `visible = FALSE`. Maybe we should not rely on that?

PS) Setting `visible = FALSE` in the call to `methods_find()` in `methods_rd()` fixes this by not omitting methods if they aren't visible and things work as expected.

**Comment by hadley** [comment]
Oh yeah, the majority of methods should not be visible (because they're registered, not exported). Want to do a PR?  (I assume the code already silently removes S3 methods that don't have documentation)
