### ISSUE TITLE
Testing `generics` ideas

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/generics#20]
I've come up with a few ideas for testing `generics`. They all revolve around testing the output of `generics:::methods_rd()`. I think I'm in favor of number 3, but am open to improvements / suggestions.

---

1) Suggest other packages such as `lubridate` or `broom` and library them when testing to have methods registered for `methods_rd()` to find.

_Pros:_

* Can test the output of multiple packages to ensure the rd is correct
* Easy to do

_Cons:_

* Adding heavy dependencies to Suggests 
* Slightly reliant on the names of the Rd files of these packages when testing against "known" output of `methods_rd()`. If the Rd file names change, the tests could break.

---

2) Create a `genericstests` package that extends `generics` and adds some methods with documentation. Then Suggest it in `generics` and library it when testing so `methods_rd()` can find the methods.

_Pros:_

* Lightweight

_Cons:_

* One more package to manage

---

3) Maintain un-exported methods in `generics` that can be used for testing, and dynamically register them when it is time to test. These un-exported methods have their own documentation pages. I'm testing that out in a branch. [Here](https://github.com/DavisVaughan/generics/blob/testing-dynamic-docs/R/hidden.R) is the R file with the methods and their docs. [Here](https://github.com/DavisVaughan/generics/blob/testing-dynamic-docs/tests/testthat/test-dynamic-docs.R) is the test file that dynamically registers the methods and has some explanation of this.

_Pros:_

* Lightweight
* Contained in 1 package

_Cons:_

* Somewhat complicated
* Can't test interactively with `devtools::test()` (but can test manually by installing and then running that test file, or by running R CMD Check)

[Passing travis](https://travis-ci.org/DavisVaughan/generics/builds/435859951)

**Comment by hadley** [comment]
I think 3 sounds good. Two suggestions:

1. See if you can figure out how to unregister an S3 method (@jimhester might know since presumably pkgload has to do this), and then unregister in a `teardown()` block

1. Docs should be `@keyword internal`
