### ISSUE TITLE
Add generics for repr?

### ISSUE THREAD

**Issue by egnha** [r-lib/generics#31]
The [IRKernel](https://github.com/IRkernel/IRkernel) currently relies on the [repr](https://github.com/IRkernel/repr) package to provide generics for displaying Jupyter cell outputs. Adding repr generics would enable package writers to ensure that S3 objects print in the Jupyter console/notebook as they would in the R REPL.

**Comment by topepo** [comment]
Are there specific generics (that sounds weird) that you would like to propose?

**Comment by egnha** [comment]
Perhaps `repr_text()` and `repr_html()` from [generics.r](https://github.com/IRkernel/repr/blob/master/R/generics.r) in the repr package. (There are other methods, but these two are the ones typically invoked for cell outputs.)

**Comment by hadley** [comment]
In order to keep generics reasonably scoped, I think at least one tidyverse package would need to export it any candidate funtion.
