### ISSUE TITLE
Add a compress(x, ...) generic

### ISSUE THREAD

**Issue by krivit** [r-lib/generics#47]
It is currently used by at least two packages (`quanteda` (albeit deprecated) and `wavethresh`), and some of my packages have planned uses for them as well.

I would be happy to submit a PR.

**Comment by hadley** [comment]
We're currently keeping generics focussed on functions that we need in multiple places in the tidyverse; I don't want it to become a big ocean of every possible generic that might be used across multiple packages.

**Comment by krivit** [comment]
> We're currently keeping generics focussed on functions that we need in multiple places in the tidyverse; I don't want it to become a big ocean of every possible generic that might be used across multiple packages.

Belated thanks for addressing this. I really wish it were otherwise, since a generic (no pun intended) package like that would be a valuable service, particularly with an easily discoverable name like this. For future reference, can I ask you to please document this somewhere in package description and/or documentation?
