### ISSUE TITLE
Re-licensing generics as MIT

### ISSUE THREAD

**Issue by hadley** [r-lib/generics#49]
I have reviewed all non-RStudio [contributors](https://github.com/r-lib/generics/graphs/contributors). I think the following contribution[s] are significant enough to merit a potential copyright claim:​

* [x] [those made](https://github.com/r-lib/generics/commits?author=mitchelloharawild) by @mitchelloharawild  
* [x] [those made](https://github.com/r-lib/generics/commits?author=alexpghayes) by @alexpghayes  

@mitchelloharawild, @alexpghayes, would you give your permission to relicense generics as MIT? If so, please comment "I agree" below.

**Comment by alexpghayes** [comment]
Yeah all good by me.

**Comment by mitchelloharawild** [comment]
I agree.
