### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by rickyars** [r-lib/generics#51]
On CRAN, the license is listed as GPL-2. On GitHub, the license is listed as MIT. I think this is just an issue with docs/index.html (there are also a few files in tests/testthat which also mention GPL-2). Perhaps the documentation needs to be updated. btw, i'm super glad to see this package is not GPL-2.

**Comment by hadley** [comment]
We've just relicensed it, so technically the version on CRAN is GPL, but the next release (happening v. soon) will be MIT.
