### ISSUE TITLE
Add forecast() and accuracy() generics

### ISSUE THREAD

**Issue by robjhyndman** [r-lib/generics#63]
It has been suggested that the `forecast()` and `accuracy()` generic functions would be better placed in the `generics` package, rather than having them duplicated across several packages, or importing the `forecast` package just to use these functions. Would you be willing to consider this? If yes, do you want a PR? @mitchelloharawild @config-i1

**Comment by config-i1** [comment]
It would be great if this was implemented in `generics`. This would resolve issues that several users have complained about over the recent years. Let me know if I can help to make this happen :).

**Comment by config-i1** [comment]
I've created a pull request with the two generics to simplify things, if it helps :)

**Comment by mitchelloharawild** [comment]
Thanks for the PR, it would be nice to use `generics()` for these functions.
